using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace RequestFlow.Infrastructure {
    public class InfoHandler : IHttpHandler {

        public void ProcessRequest(HttpContext context) {

            if (context.Request.RawUrl == "/Test/Index") {
                context.Server.TransferRequest("/Home/Index");
            } else {
                context.Response.Write("Content generated by InfoHandler");
            }
        }

        public bool IsReusable {
            get { return false; }
        }
    }
}
